project:
  type: website

website:
  title: "Hugo Carvalho"

  page-navigation: true
  site-url: "https://hugocarvalho.mat.br/"
  repo-url: "https://github.com/HugoCarvalhoUFRJ/site"
  repo-actions: [edit, source, issue]

  page-footer:
    right: "Page built in [Quarto](https://quarto.org/)."
    left: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://hugocarvalhoufrj.github.io/site/">This website</a> (by <span property="cc:attributionName">Hugo Carvalho</span>), its content and everything related to it is licensed under <a href="http://creativecommons.org/licenses/by-nc/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-NC 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/nc.svg?ref=chooser-v1"></a></p>

  google-analytics: G-RH0WQSR1XC
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: ensino.qmd
        text: Ensino
      - href: orientacoes.qmd
        text: Orientações
      - href: compositions.qmd
        text: Music compositions
      # - href: blog.qmd
      #   text: Blog

# bibliography: refs.bib

format:
  lcars-html: default
