---
title: Orientações
description: (em Português)
format: lcars-html
toc: true
---

::: {.callout-warning}
Página ainda em construção. Última atualização: 13/07/2025.
::: 

## Orientações em andamento
### Doutorado
* Pedro Faria Proença Gomes. *Elaboração de Sistemas Composicionais Utilizando Métodos de Inferência Fuzzy*. Mestrado em Música -- UFRJ. Co-orientação em conjunto com Liduino Pitombeira.

### Mestrado
* Matheus Raposo Lopes Saléh Amado. *Inferência Variacional*. Mestrado em Estatística -- UFRJ. Co-orientador: Carlos Zanini.

### Trabalho de Conclusão de Curso
* Iran Cruz Soares. Tema da pesquisa: *Inferência variacional semi-implícita*. Bacharelado em Estatística -- UFRJ.

* Stefane Moraes Castoldi. *Identificação de Estruturas Melódicas na MPB por Modelos de Tópicos*. Bacharelado em Estatística -- UFRJ.

### Iniciação Científica
* Rumenick Brandi Sigolo e Frederico Strasser. *Identificação de Estruturas Rítmicas na MPB por Modelos de Tópicos*. Bacharelado em Matemática Aplicada -- UFRJ.

## Orientações finalizadas
### Mestrado
* Karolayne Pereira Dessabato (2025) *Machine Learning Methods in Music Emotion Recognition*. Mestrado em Estatística -- UFRJ.

* Natanael Luciano de Matos (2024) *Aplicação de Redes Neurais Radiais em Identificação de Gêneros Musicais*. Mestrado em Estatística -- UFRJ. Co-orientador: Carlos Zanini.

* Natan Freitas Leite (2022) *Modelagem Estatística Multivariada da Relação entre Treinamento e Performance no Ciclismo*. Mestrado em Estatística -- UFRJ. Co-orientação em conjunto com Carlos Zanini.

* Catarina Dall'Agnol Zidde (2022) *Denoising Face Images Using Convolutional Autoencoders*. 2022. Mestrado em Estatística -- UFRJ. Co-orientação em conjunto com Ralph Silva.

* Dimas Soares Lima (2022) *Flexible Colaborative Filtering: A Bayesian Approach*. Mestrado em Estatística -- UFRJ. Co-orientação em conjunto com Marina Paez.

* Pedro Faria Proença Gomes (2022) *Formalização Computacional de Sistemas Composicionais a partir de Ferramentas Analíticas*. Mestrado em Música -- UFRJ. Co-orientação em conjunto com Liduino Pitombeira.

* Felipe Pagginelli Patrício (2020) *The Johnson-Lindenstrauss Lemma*. Mestrado em Matemática -- UFRJ. Co-orientação em conjunto com Wladimir Neves.

### Trabalho de Conclusão de Curso
* André Duarte de Matos Pataro e Marco Antonio Mourão de Almeida (2024) *Estudo Sobre a Incidência do Suicídio no Brasil*. Bacharelados em Ciências Atuariais e Estatística -- UFRJ.

* Rodrigo Côrtes Nogueira da Rocha Pita (2024) *Identificação de Acordes via Modeos de Markov Ocultos Musicalmente Informados*. Bacharelado em Ciência da Computação -- UFRJ. Co-orientação em conjunto com João Paixão.

* Arthur Araújo Freira e Renan Rios de Souza (2023) *A Contribuição da Modelagem das Curvas de perda para o Entendimento do Seguro Rural no Brasil*. Bacharelado em Ciências Atuariais -- UFRJ.

* Vinícius da Silva Rodrigues (2023) *Aplicação da Fatoração Bayesiana de Matrizes Não-Negativas em Processamento de Música*. Bacharelado em Estatística -- UFRJ.

* Althayr Santos de Nazaret (2022) *O Uso de Modelos de Aprendizado Supervisionado para Ranqueamento por Relevância em Sistemas de Recuperação de Informação*. Bacharelado em Estatística -- UFRJ. Co-orientador: Eduardo Freitas Mangeli de Brito

* Mariane Batista dos Santos (2021) Inferência Variacional: *Uma Revisão do Caso de Mistura de Normais e uma Aplicação em Interpolação de Amostras Perdidas no Contexto de Restauração de Áudio*. Bacharelado em Estatística -- UFRJ.

* Nathalie Fernanda Toffani Magliano di Domenico Fraçatho Deziderio (2021) *O Uso de Inferência Variacional para Reconhecimento de Emoções em Música*. Bacharelado em Estatística -- UFRJ.

### Iniciação Científica
EM CONSTRUÇÃO