---
title: Research
format: lcars-html
toc: true
---

## Books
* Almada, C.; Mathias, C.; Saraiva, C.; Moreira, D.; **Carvalho, H.**; Pitombeira, L. (editors); "Schoenberg: Music and Theory". MusMat Series. 2024. [[PDF](https://musmat.org/series/vol-1.html)]

## Journal papers
* Almada, C.; **Carvalho, H.**; "Entropy, Probabilistic Harmonic Space, and the Harmony of Antonio Carlos Jobim". Musica Theorica, v. 7, n. 1. 2023. [[PDF](https://revistamusicatheorica.tema.mus.br/index.php/musica-theorica/article/view/202)]
* Pareyon, G. **et al.** "Music and Mathematics in Latin America: Major Developments in the Last 25 Years". MusMat: Brazilian Journal on Music and Mathematics, v. 6, n. 1. 2022. [[PDF](https://musmat.org/wp-content/uploads/2022/06/02-Pareyon-et-al-V6N1_2022.pdf)]
* Almada, C.; Mathias, C.; Saraiva, C.; Moreira, D.; **Carvalho, H.**; Pitombeira, L. "Celebrating 10 Years of the MusMat Research Group: Survey of Activities and Future Perspectives". MusMat: Brazilian Journal on Music and Mathematics, v. 6, n. 1. 2022. [[PDF](https://musmat.org/wp-content/uploads/2022/06/03-Almada-et-al-V6N1_2022.pdf)]
* **Carvalho, H.** "Toward a Probabilistic Fourier Analysis on Audio Signals". MusMat: Brazilian Journal on Music and Mathematics, v. 5, n. 1. 2021. [[PDF](https://musmat.org/wp-content/uploads/2021/12/01-Carvalho-V5N2_2021.pdf)]
* Ferreira, E.; Santos, R.; Lima, F.; **Carvalho, H.**; Pitombeira, L. "Sistema Composicional Intermarkoviano". Revista Vórtex, v. 8, 2020. [[PDF](https://periodicos.unespar.edu.br/index.php/vortex/article/view/3794)]
* **Carvalho, H.**; Ávila, F. R.; Biscainho, L. W. P. "Bayesian Restoration of Audio Degraded by Low-Frequency Pulses Modeled via Gaussian Process". IEEE Journal of Selected Topics in Signal Processing, v. 15, n. 1. 2021. [[IEEE Xplore](https://ieeexplore.ieee.org/document/9238480)]
* **Carvalho, H.** "An Introduction to Markov Chains in Music Composition and Analysis". MusMat: Brazilian Journal on Music and Mathematics, v. 4, n. 2. 2019. [[PDF](https://musmat.org/wp-content/uploads/2019/12/06-Carvalho.pdf)]
* Nunes, R. D.; Romeiro, N. C.; **Carvalho, H.**; Moreira, J. R.; Sola-Penna, M.; Silva-Neto, M. A. C.; Braz, G. R. C. "Unique PFK regulatory property from some mosquito vectors of disease, and from Drosophila melanogaster". Parasites & Vectors, v. 9. 2016. [[PDF](https://parasitesandvectors.biomedcentral.com/articles/10.1186/s13071-016-1391-y)]
* Ávila, F. R.; **Carvalho, H.**; Biscainho, L. W. P.  "Bayesian Blind Identification of Nonlinear Distortion with Memory for Audio Applications". IEEE Signal Processing Letters, v. 23. 2016. [[IEEE Xplore](https://ieeexplore.ieee.org/document/7397911)]
* Alves-Bezerra, M.; **Tremonte, H.**; Almeida, C. B.; Grillo, L. A. M.; Sola-Penna, M.; Majerowicz, D.; Braz, G. R. C.; Gondim, K. C.; Paiva-Silva, G. O. "Serotonin regulates an acyl-CoA-binding protein (ACBP) gene expression in the midgut of Rhodnius prolixus". Insect Biochemistry and Molecular Biology, v. 40. 2010. [[ScienceDirect](https://www.sciencedirect.com/science/article/abs/pii/S0965174810000032)]

## Conference papers
* Matos, N. L.; **Carvalho, H.**; Zanini, C. T. P. "'Shallow' Neural Network Architectures for Musical Genre Classification". Proceedings of the 1st Latin American Music Information Retrieval Workshop (LAMIR). 2025. [[PDF](https://zenodo.org/records/14908040)]
* **Carvalho, H.**; Martins, F. D.; Almada, C. de L. "A Corpus Study of Rhythm in Brazilian Popular Music". Proceedings of the 1st Latin American Music Information Retrieval Workshop (LAMIR). 2025. [[PDF](https://zenodo.org/records/14908040)]
* **Carvalho, H.**; Li, M. S.; di Luca, M.; Wing, A. M. "A Kalman Filter model for synchronization in musical ensembles". Proceedings of the 25th International Society for Music Information Retrieval (ISMIR 2025). 2025. [[PDF](https://ismir2024program.ismir.net/poster_347.html)]
* Matos, N. L.; **Carvalho, H.** "Uma implementação eficiente em Python de um algoritmo de separação de fontes sonoras". Proceedings of the VI International Conference on Music and Mathematics (MusMat 2021). 2021. [[PDF](https://musmat.org/wp-content/uploads/2022/06/04_DeMatos_Carvalho.pdf)]
* Carvalho, L. F. V.; **Carvalho, H.** "A system based on sinusoidal analysis for the estimation and compensation of pitch variations in musical recordings". Proceedings of the 20th International Conference on Digital Audio Effects (DAFx'17). 2017. [[PDF](http://dafx17.eca.ed.ac.uk/papers/DAFx17_paper_77.pdf)]
* **Carvalho, H.**; Ávila, F. R.; Biscainho, L. W. P. "Bayesian suppression of memoryless nonlinear audio distortion". Proceedings of the 23rd European Signal Processing Conference (EUSIPCO 2015). 2015. [[PDF](https://www.eurasip.org/Proceedings/Eusipco/Eusipco2015/papers/1570103841.pdf)]
* **Carvalho, H.**; Ávila, F. R.; Biscainho, L. W. P. "A Bayesian Procedure for Restoration of Audio Signals Degraded by Low-frequency Pulses". Proceedings of the 12th Conference in Audio Engineering of the AES-Brazil (AES-Brasil 2014). 2014.
